echo $track;
//[#]this to put all the reference buttons in a box
echo "<div >";
/*calculate number of referer button to be made by dividing the total number of
 records generated by number of 
records to shown on a single page*/

$no_of_button = (int)(($count/$maxi)-1);
//initialize a button counter
$countbutton = 0;
/*create referer  buttons. The referer buttons are created using form with hidden input that takes
 *index to start the page it is refering to as value, when submitted, it loads index.php passing the
 *value along with GET method.*/
 
	while($countbutton<=$no_of_button){
/* $buttonvalue set tag on each refering button, it takes the value returned by pagereferertag()*/
		$buttonvalue = pagereferertag($countbutton,0,($no_of_button));
		
		$goto = $countbutton*$maxi;
		if(isset($_GET['next'])){
			if($countbutton==($_GET['next']/$maxi)){
			$bgcolor = '#6D0AAA';
			$fcolor='white';
		}
		else{
			$bgcolor='#eeeeee';
			$fcolor="#6D0AAA";
		}}else{ $bgcolor = '#eeeeee';$fcolor="#6D0AAA";}
		$action = basename($_SERVER['PHP_SELF']);
		$pagebutton = "<form style=\"display:inline-block\" action=\"$action\" method=\"GET\">
		<input name=\"next\" type=\"hidden\" value=\"$goto\"/>
		<input id=\"page\" style=\"background-color:$bgcolor; color:$fcolor;\"type=\"submit\" value=\"$buttonvalue\"/>
		</form>";
		
		echo $pagebutton;
		$countbutton++;
		}
	echo "<button style=\"display:inline-block;; border:0px\" >page</button>";
	//[#]
	echo "</div>";
	